In [1]:
import pandas as pd

data={
'Age':[25,30,28,40,35,29,45,32,38,27],
'MonthlyIncome':[30000,45000,35000,70000,50000,32000,85000,48000,62000,31000],
'JobSatisfaction':[2,3,2,4,3,1,4,2,3,1],
'OverTime':['Yes','No','Yes','No','Yes','Yes','No','Yes','No','Yes'],
'YearsAtCompany':[1,5,2,10,6,2,15,4,8,1],
'WorkLifeBalance':[2,3,2,4,3,1,4,2,3,2],
'Attrition':['Yes','No','Yes','No','No','Yes','No','Yes','No','Yes']
}

df=pd.DataFrame(data)

df

,Age,MonthlyIncome,JobSatisfaction,OverTime,YearsAtCompany,WorkLifeBalance,Attrition
0,25,30000,2,Yes,1,2,Yes
1,30,45000,3,No,5,3,No
2,28,35000,2,Yes,2,2,Yes
3,40,70000,4,No,10,4,No
4,35,50000,3,Yes,6,3,No
5,29,32000,1,Yes,2,1,Yes
6,45,85000,4,No,15,4,No
7,32,48000,2,Yes,4,2,Yes
8,38,62000,3,No,8,3,No
9,27,31000,1,Yes,1,2,Yes

In [2]:
from sklearn.preprocessing import LabelEncoder

df["Attrition"]=df["Attrition"].map({
"Yes":1,
"No":0
})

df["OverTime"]=df["OverTime"].map({
"Yes":1,
"No":0
})

df

,Age,MonthlyIncome,JobSatisfaction,OverTime,YearsAtCompany,WorkLifeBalance,Attrition
0,25,30000,2,1,1,2,1
1,30,45000,3,0,5,3,0
2,28,35000,2,1,2,2,1
3,40,70000,4,0,10,4,0
4,35,50000,3,1,6,3,0
5,29,32000,1,1,2,1,1
6,45,85000,4,0,15,4,0
7,32,48000,2,1,4,2,1
8,38,62000,3,0,8,3,0
9,27,31000,1,1,1,2,1

In [4]:
from sklearn.model_selection import train_test_split

X=df.drop("Attrition",axis=1)
y=df["Attrition"]

X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.2,random_state=42
)

In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt=DecisionTreeClassifier()

dt.fit(X_train,y_train)

pred=dt.predict(X_test)

print(accuracy_score(y_test,pred))

1.0

In [6]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

rf.fit(X_train,y_train)

pred2=rf.predict(X_test)

print(accuracy_score(y_test,pred2))

0.5